# Generated by Django 3.1.7 on 2021-10-13 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'Žena'), ('M', 'Muž'), ('U', 'Neuvádět')], default='U', max_length=10)),
                ('account_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('stock', models.IntegerField()),
                ('price_euro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_czk', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=31)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customer')),
                ('items', models.ManyToManyField(to='main.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress_line_one', models.CharField(max_length=255)),
                ('adress_line_two', models.CharField(max_length=255)),
                ('suite', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('CZ', 'Česká Republika'), ('DE', 'Německo'), ('AU', 'Rakousko'), ('PL', 'Polsko'), ('SK', 'Slovensko')], max_length=100)),
                ('zip_code', models.CharField(max_length=15)),
                ('customer', models.ManyToManyField(to='main.Customer')),
            ],
        ),
    ]
